### ISSUE TITLE
matplotlib get messed up due to import of holoviews

### ISSUE THREAD

**Issue by zym1010** [ioam/imagen#48] opened 2016-05-09 14:31 UTC
Hi,

I've been using imagen for a while, for generating a bunch of stimuli in the lab. It's great. However, it has a side effect of importing holoview related stuff and messed up the default plotting style of matplotlib completely in jupyter notebook. Also, importing `imagen` seems to change the matplotlib backend to 'agg' silently, and it makes inline plot using vanilla matplotlib fail.

Is there any way to solve this? Thanks.

**Comment by jbednar** [comment] 2016-05-09 14:41
Glad you are finding it useful.  That's an excellent question!  Historically, imagen had no dependence on holoviews, but it included certain files that we needed to develop further in holoviews, so we switched it around so that those files moved to holoviews and changed imagen to import them from there.  So imagen only relies on a very small part of holoviews, and it should be very feasible to make sure we only import those parts and not any of the plotting-related functionality that would interact with matplotlib.  

@jlstevens and @philippjfr, what's the status of being able to import the "core" bits of holoviews without any additional dependencies?  Does this still require changes to holoviews, or were those changes already made a while back?  I can't find a holoviews issue for this.

**Comment by philippjfr** [comment] 2016-05-09 14:41
I'll have to think about it a bit. There should be a way to import holoviews without initializing the plotting backends and thereby changing the matplotlib options but afaik it isn't currently possible.

>@jlstevens and @philippjfr, what's the status of being able to import the "core" bits of holoviews without any additional dependencies?

You can import the core bits of holoviews without any of the dependencies, the problem is that if the dependencies are available it will just go ahead and import it.

**Comment by zym1010** [comment] 2016-05-09 14:48
@philippjfr  @jbednar  thanks for quick response!

**Comment by jbednar** [comment] 2016-05-09 14:57
That's right.

**Comment by zym1010** [comment] 2016-05-09 15:04
@jbednar  sounds great! so I guess a minimal way of fixing this problem would be somehow loading those plotting-related functions in imagen in a lazy fashion.

**Comment by philippjfr** [comment] 2016-05-09 15:08
I don't think there is any way around modifying holoviews to ensure the plotting backends don't get loaded on import. We should do this anyway and it already is an existing issue in HoloViews (https://github.com/ioam/holoviews/issues/528). We're aiming for a HoloViews release later this week and that should be part of it.

**Comment by zym1010** [comment] 2016-05-09 15:15
@philippjfr thanks!

**Comment by philippjfr** [comment] 2016-05-11 13:41
The PR fixing this in holoviews has now been merged and we'll have a new release later today. Closing.

**Closed by philippjfr** 2016-05-11 13:41 UTC
